name: abdullah
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.0.6 <3.0.0"

dependencies:
  introduction_screen: ^2.1.0
  intro_views_flutter:
    git: git://github.com/aagarwal1012/IntroViews-Flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bottom_navy_bar: ^5.6.0
  http: ^0.13.3
  carousel_slider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/
    - assets/images/1.jpg

  uses-material-design: true
  fonts:
    - family: DoHyeon
      fonts:
        - asset: assets/fonts/DoHyeon-Regular.ttf
